services:
  db:
    image: postgis/postgis
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - "5432:5432"
  geoserver:
    build:
      context: .
      dockerfile: geoserver.Dockerfile
    environment:
      PG_HOST: db
    depends_on:
      - db
    ports:
      - 8080:8080
  setup:
    build:
      context: .
      dockerfile: setup.Dockerfile
    depends_on:
      - db
      - geoserver
    links:
      - db
      - geoserver
    environment:
      PGPASSWORD: mysecretpassword
      PG_HOST: db
      GEOSERVER_HOST: geoserver
      PG_PORT: 5432
      GEOSERVER_PORT: 8080
    restart: "no"   
